config/routes.rb
Rails.application.routes.draw do
  root 'programming_languages#index'
  resources :programming_languages
  
  get 'programming_languages/index'
  get 'programming_languages/show'

  get 'programming_languages/new',
  to: 'programming_languages#new',
  as: 'new_programming_language_path'

  get 'programming_languages/create'

  get 'programming_languages/edit',
  to: 'programming_languages#edit',
  as: 'edit_programming_language_path'

  get 'programming_languages/update'
  
  get 'programming_languages/destroy',
  to: 'programming_languages#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/programming_languages_controller.rb
class ProgrammingLanguagesController < ApplicationController

  def index
    @programming_languages = ProgrammingLanguage.all
  end

  def show
    @language = ProgrammingLanguage.find(params[:id])
  end

  def new
    @language = ProgrammingLanguage.new
  end

  def create
    @language = ProgrammingLanguage.new(programming_language_params)
    if @language.save
      redirect_to programming_language_path(@language), notice: 'Programming language was successfully added.'
    else
      render :new
    end
  end

  def edit
    @language = ProgrammingLanguage.find(params[:id])
  end

  def update
    @language = ProgrammingLanguage.find(params[:id])
    @language.update(programming_language_params)
    if @language.save
      redirect_to programming_language_path(@language), notice: 'Programming language was successfully edited.'
    else
      render :edit
    end
  end

  def destroy
    @language = ProgrammingLanguage.find(params[:id])
    @language.destroy
  end

  private 

  def programming_language_params
    params.require(:programming_language).permit(:title, :description, :link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programming_languages_helper.rb
module ProgrammingLanguagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgramLangList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programming_languages/_footer.html.erb

<div>
  <%= link_to 'Back to All Programming Languages', '/' %>
  <%= link_to 'Edit', '/programming_languages/edit/#{language.id}'  %>
  <%= form_with(model: language, url: programming_language_path(language), method: :delete, data: { confirm: 'Are you sure?' }) do |form| %>
    <%= form.submit 'Delete', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/programming_languages/create.html.erb
<h1>ProgrammingLanguages#create</h1>
<p>Find me in app/views/programming_languages/create.html.erb</p>

app/views/programming_languages/destroy.html.erb
<h1>ProgrammingLanguages#destroy</h1>
<p>Find me in app/views/programming_languages/destroy.html.erb</p>

app/views/programming_languages/edit.html.erb
<section>
<div>
<h1>Edit an Existing Programming Language</h1>

<%= form_with(model: @language, url: programming_language_path(@language), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit Edit' %>
  </div>
<% end %>

<%= link_to 'Back to All Programming Languages', '/' %>
</section>

app/views/programming_languages/index.html.erb
<h1>Programming Languages</h1>
<div>
  <% @programming_languages.each do |language| %>
    <h1><%= language.title %></h1>
    <ul>
    <li>
      <%= link_to "More information about #{language.title}", programming_language_path(language) %>
    </li>
    <li>
      <%= link_to 'Edit', edit_programming_language_path(language)  %>
    </li>
    </ul>
    <%= form_with(model: language, url: programming_language_path(language), method: :delete, data: { confirm: 'Are you sure?' }) do |form| %>
      <%= form.submit 'Delete', class: 'btn btn-danger' %>
    <% end %>
  <% end %>
</div>
<div>
<%= link_to 'Add new language', new_programming_language_path %>
</div>

app/views/programming_languages/new.html.erb
<section>
<div>
<h1>Add a New Programming Language</h1>

<%= form_with(model: @language, url: programming_languages_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Language' %>
  </div>
<% end %>

<%= link_to 'Back to All Programming Languages', '/' %>
</section>

app/views/programming_languages/show.html.erb
<section>
  <h1><%= @language.title %></h1>
  <p><%= @language.description %></p>
  <%= link_to 'View documentation', @language.link %>
</section>
  <footer>
  <%= render 'footer', language: @language %>
</footer>

app/views/programming_languages/update.html.erb
<h1>ProgrammingLanguages#update</h1>
<p>Find me in app/views/programming_languages/update.html.erb</p>